# UVData configuration for pyuvdata 
# This should only include values that aren't derived from data shape
# https://pyuvdata.readthedocs.io/en/latest/uvdata.html#required
history: Created with aavs_uv 1.0.0 
instrument: aavs3
telescope_name: aavs3
telescope_ECEF_X: -2559365.6735293902
telescope_ECEF_Y: 5095376.895164881
telescope_ECEF_Z: -2849123.777644051
channel_spacing: 781250.0           # Channel spacing in Hz
channel_width: 925926.0             # 781250 Hz * 32/27 oversampling gives channel width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
vis_units: uncalib
# PyUVData specific keywords 
flex_spw: False                   
future_array_shapes: False
Nspws: 1
Nphase: 1