# UVData configuration for pyuvdata 
# This should only include values that aren't derived from data shape
# https://pyuvdata.readthedocs.io/en/latest/uvdata.html#required
history: Created with aavs_uv 1.0.0 
instrument: aavs3
telescope_name: aavs3
telescope_ECEF_X: -2559365.67352939
telescope_ECEF_Y: 5095376.89516488
telescope_ECEF_Z: -2849123.77764405
channel_width: 925926.0             # Hz TODO: CHECK THIS! 781250.0 spacing after oversample?
channel_spacing: 781250.0           # Hz - oversampled so spacing is smaller than width
antenna_locations_file: antenna_locations.txt
baseline_order_file: baseline_order.txt
flex_spw: False
polarization_type: linear_crossed  # stokes, circular, linear (XX, YY, XY, YX) or linear_crossed (XX, XY, YX, YY)
future_array_shapes: False
vis_units: uncalib
Nspws: 1
Nphase: 1