[tool.poetry]
name = "aavs-uv"
version = "1.6.0"
description = "SKA-low Aperture Array Verification Systems (AAVS) Interferometry UV utilities."
authors = ["Danny C. Price"]
license = "BSD"
repository = "https://github.com/ska-sci-ops/aavs_uv"
documentation = "https://github.com/ska-sci-ops/aavs_uv"
include = [
  { path = "config"},
  { path = "datamodel"} 
]

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
astroplan = ">=0.9"
astropy = ">=5.3"
h5py = ">=3.9"
numpy = ">=1.24"
pandas = ">=2.0"
xarray = ">=2023.7"
loguru = ">=0.5"
tqdm = ">4.0"
pyyaml = ">=5.0"
pyuvdata = ">=2.4.1"
pygdsm = ">=1.3"
ska-sdp-func-python = "0.3.2"
ska-sdp-datamodels = "0.2.6"

[tool.poetry.group.casa]
optional = true

[tool.poetry.group.casa.dependencies]
python-casacore = {version = ">=3.5"}

[tool.poetry.scripts]
aavs_uv = "aavs_uv.converter:run"

[tool.poetry.extras]
python-casacore = ["python-casacore"]

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = ">=7.4"
pytest-cov = ">=3.0"
colored = ">=2.2"

[tool.poetry.group.docs.dependencies]
sphinx = ">=7.2"
sphinx-rtd-theme = ">=1.3"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
