[tool.poetry]
name = "aavs-uv"
version = "1.4.0"
description = "SKA-low Aperture Array Verification Systems (AAVS) Interferometry UV utilities."
authors = ["Danny C. Price"]
license = "Apache 2.0"
repository = "https://github.com/ska-sci-ops/aavs_uv"
documentation = "https://github.com/ska-sci-ops/aavs_uv"
include = [
  { path = "config"}
]

[tool.poetry.dependencies]
python = ">=3.10"
astroplan = ">=0.9"
astropy = ">=5.3"
h5py = ">=3.9"
numpy = ">=1.24"
pandas = ">=2.0"
xarray = ">=2023.7"
loguru = ">=0.5"
tqdm = ">4.0"

# optional dependencies; used by "extras"
python-casacore = {version = "^3.5", optional = true}

[tool.poetry.scripts]
aavs_uv = "aavs_uv.converter:run"

[tool.poetry.extras]
python-casacore = ["python-casacore"]

[tool.poetry.dev-dependencies]
pytest = ">=7.4"
pytest-cov = ">=3.0"
colored = ">=2.2"

[tool.poetry.group.docs.dependencies]
sphinx = ">=7.2"
sphinx-rtd-theme = ">=1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
